name:  # Environment name

dependencies:  # Packages should be installed through conda if possible
  - python=  # Python version
  - pre-commit
  - ruff

  - pip:  # Install additional packages through pip if they're not available in the default conda channel
